(Fri Sep  6 12:55:14 2024)(-0.406276 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
Could not find plugin library "/home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/lib/libscanner_great.so".

Raised at: line 361 in function Gambit::Scanner::Plugins::Plugin_Loader::Plugin_Loader() of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0231606 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_dynesty" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_dynesty.py(14): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0241477 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_emcee" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_emcee.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0252146 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_nautilus" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_nautilus.py(6): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0259812 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_nessai" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_nessai.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0267185 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_pocomc" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_pocomc.py(10): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0275101 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_scipy" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_scipy.py(6): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0282589 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_ultranest" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_ultranest.py(9): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0290096 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_zeus" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_zeus.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0294139 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"grid" was not loaded: ModuleNotFoundError: No module named 'scanner_plugin'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/grid.py(12): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0361675 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_dynesty" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_dynesty.py(14): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0369028 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_emcee" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_emcee.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0376421 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_nautilus" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_nautilus.py(6): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0383889 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_nessai" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_nessai.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0391201 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_pocomc" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_pocomc.py(10): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0398728 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_scipy" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_scipy.py(6): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0553548 [s])[Default,Utilities]:
Random number engine mt19937_64 (default) selected with seed 1806051843.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0406847 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_ultranest" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_ultranest.py(9): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0414149 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"gambit_zeus" was not loaded: ModuleNotFoundError: No module named 'scannerbit'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/mpi.py(1): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/utils/__init__.py(3): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/gambit_zeus.py(8): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0418068 [s])[Default,Scanner][Warning][Non-fatal]:
WARNING: A problem has been raised by ScannerBit.
"grid" was not loaded: ModuleNotFoundError: No module named 'scanner_plugin'

At:
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/ScannerBit/src/scanners/python/plugins/grid.py(12): <module>
  <frozen importlib._bootstrap>(241): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(883): exec_module
  <frozen importlib._bootstrap>(703): _load_unlocked
  <frozen importlib._bootstrap>(1006): _find_and_load_unlocked
  <frozen importlib._bootstrap>(1027): _find_and_load
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(112): _run_scan
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(23): process_func
  /usr/lib64/python3.10/multiprocessing/process.py(108): run
  /usr/lib64/python3.10/multiprocessing/process.py(314): _bootstrap
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(71): _launch
  /usr/lib64/python3.10/multiprocessing/popen_fork.py(19): __init__
  /usr/lib64/python3.10/multiprocessing/context.py(281): _Popen
  /usr/lib64/python3.10/multiprocessing/context.py(224): _Popen
  /usr/lib64/python3.10/multiprocessing/process.py(121): start
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/processify.py(43): wrapper
  /home/gmartine/.local/lib/python3.10/site-packages/pyscannerbit/scan.py(329): scan
  /home/gmartine/pyscannerbit/tests/test_all_scanners.py(63): <module>


Raised at: line 240 in function void Gambit::Scanner::Plugins::Plugin_Loader::Load_PyPlugins(const string&) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/ScannerBit/src/plugin_loader.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.056107 [s])[Default][Info]:
No previous output file found, treating run as completely new.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0570759 [s])[Default,Core]:
Starting scan.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0774091 [s])[Default,Printers][Info]:
Assigned printer ID '0' to output quantity with label 'LogLike'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0774832 [s])[Default,Printers][Info]:
Assigned printer ID '1' to output quantity with label 'pointID'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0775098 [s])[Default,Printers][Info]:
Assigned printer ID '2' to output quantity with label 'MPIrank'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0780563 [s])[Default,Printers][Info]:
Assigned printer ID '3' to output quantity with label 'Posterior'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0780868 [s])[Default,Printers][Info]:
Assigned printer ID '4' to output quantity with label 'LastLive'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0790296 [s])[Default,Printers][Info]:
Assigned printer ID '5' to output quantity with label 'default::z'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0791113 [s])[Default,Printers][Info]:
Assigned printer ID '6' to output quantity with label 'default::y'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0791481 [s])[Default,Printers][Info]:
Assigned printer ID '7' to output quantity with label 'default::x'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:14 2024)(0.0793358 [s])[Default,Printers][Info]:
Assigned printer ID '8' to output quantity with label 'ModifiedLogLike'
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:16 2024)(2.04729 [s])[Default,Printers][Info]:
Gathering sync buffer data from all processes to rank 0 process...
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:16 2024)(2.04737 [s])[Default,Printers][Info]:
Gathering data on number of points and buffers to be transmitted
Number of points to send from this process: 670
Number of buffers to send from this process: 7

--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:16 2024)(2.0474 [s])[Default,Printers][Info]:
Gathered data:
Number of points to recv from each process: [670 ]
Number of buffers to recv from each process: [7 ]

--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:16 2024)(2.04862 [s])[Default,Printers][Info]:
Gathering buffer data for processes [0 ]
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:16 2024)(2.06268 [s])[Default,Printers][Info]:
Gathering buffer block size data (number of buffer blocks to transmit from this process: 67)
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:16 2024)(2.06278 [s])[Default,Printers][Info]:
Performing Gatherv of buffer data blocks...
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:16 2024)(2.08155 [s])[Default,Printers][Info]:
Resynchronising print buffers:
   Buffer contains 670 items (name=LogLike)
   Buffer contains 670 items (name=MPIrank)
   Buffer contains 670 items (name=ModifiedLogLike)
   Buffer contains 670 items (name=default::x)
   Buffer contains 670 items (name=default::y)
   Buffer contains 670 items (name=default::z)
   Buffer contains 670 items (name=pointID)

  Initial N points   : 0
  Final N points     : 670
  Difference N points: 670

Print buffer now contains 670 items.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:16 2024)(2.09313 [s])[Default,Printers][Error][Fatal]:
ERROR: A problem has occurred in the printer utilities.
Error opening existing dataset (with name="lastPointID") in HDF5 file. H5Dopen2 failed.
You may have a corrupt hdf5 file from a previous run. Try using -r, or deleting the old output.
Raised at: line 210 in function void Gambit::Printers::HDF5DataSetBase::open_dataset(hid_t) of /tmp/pip-req-build-i3g8qoin/pyscannerbit/scannerbit/untar/ScannerBit/Printers/src/printers/hdf5printer_v2/hdf5printer_v2.cpp.
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:16 2024)(2.09364 [s])[Default,Utilities][Info]:
rank 0: Entered BarrierWithTimeout (with tag 6666)
--<>--<>--<>--<>--<>--<>--<>--
(Fri Sep  6 12:55:16 2024)(2.09369 [s])[Default,Utilities][Info]:
rank 0: Synchronisation succeeded in BarrierWithTimeout (tag=6666)!
--<>--<>--<>--<>--<>--<>--<>--
